DELETE FROM triage_rules;
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('chest_pain_possible_heart_attack', 'Chest pain / possible heart attack', 'cardio', 'AE', 'chest pain; chest tightness; pressure in chest; pain radiating to arm/jaw; sweating with chest pain; shortness of breath with chest pain', 'sudden severe pain; fainting; severe breathlessness; blue lips; known heart disease; pain >10 minutes', 'Stop activity, sit or lie in a comfortable position. Call emergency services / go to A&E now. If the person becomes unresponsive and not breathing normally, start CPR and use an AED if available.', 'Do not let them drive themselves. Do not delay to ''see if it passes''.', 'Any chest pain with the red flags above; first-ever severe chest pain; chest pain with breathing trouble.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('stroke_fast_signs', 'Stroke (FAST signs)', 'neuro', 'AE', 'face droop; one-sided weakness; arm weakness; slurred speech; sudden confusion; cannot speak; sudden vision loss', 'sudden onset', 'Go to A&E immediately. Keep them comfortable and note the time symptoms started. Do not give food or drink.', 'Do not wait for symptoms to improve.', 'Any FAST signs.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('severe_difficulty_breathing', 'Severe difficulty breathing', 'respiratory', 'AE', 'cannot breathe; severe shortness of breath; gasping; blue lips; unable to speak full sentences', 'drowsy/confused; turning blue; stridor/noisy breathing; chest pain; history of severe asthma/allergy', 'Go to A&E immediately. Keep them upright if it helps. If you have a prescribed reliever inhaler or epinephrine auto-injector, use it as directed.', 'Do not lie them flat if that makes breathing worse.', 'Any severe breathing difficulty or blue lips.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('anaphylaxis_severe_allergy', 'Anaphylaxis (severe allergy)', 'allergy', 'AE', 'allergic reaction; swollen lips; swollen tongue; hives with breathing trouble; throat tightness; wheezing after allergy; faint after sting/food', 'trouble breathing; throat swelling; dizziness/fainting; vomiting repeatedly; rapid worsening', 'Go to A&E immediately. If they have an epinephrine auto-injector, use it right away and seek emergency care.', 'Do not wait to see if it improves.', 'Any breathing trouble or fainting with an allergic reaction.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('unresponsive_not_waking_up', 'Unresponsive / not waking up', 'critical', 'AE', 'unresponsive; won''t wake up; collapsed; passed out and not responding', 'abnormal/no breathing; seizure activity; head injury; suspected poisoning', 'Go to A&E immediately / call emergency services. Check breathing. If not breathing normally, start CPR and use an AED if available.', 'Do not give food/drink. Do not leave them alone.', 'Any unresponsiveness, especially with abnormal breathing.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('seizure_fits_convulsions', 'Seizure (fits/convulsions)', 'neuro', 'AE', 'seizure; fits; convulsions; shaking uncontrollably; jerking movements', 'first seizure; seizure >5 minutes (or unknown); repeated seizures; trouble breathing; injury', 'Keep them safe: move hazards away and cushion the head. Do not restrain. When movements stop, place them on their side and monitor breathing. Go to A&E now if any red flags.', 'Do not put anything in their mouth.', 'First-ever seizure; repeated seizures; breathing problems; injury; prolonged seizure.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('severe_bleeding', 'Severe bleeding', 'injury', 'AE', 'bleeding heavily; blood won''t stop; squirting blood; large wound', 'soaking through cloths quickly; dizziness/fainting; amputation; embedded object', 'Apply firm direct pressure with a clean cloth. Keep pressure continuously. Add more cloth on top if soaked. If possible, elevate the limb. Go to A&E immediately.', 'Do not remove the first cloth to check. Do not pull out embedded objects (pad around them).', 'Bleeding that is heavy or hard to control; faintness.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('head_injury_with_red_flags', 'Head injury with red flags', 'injury', 'AE', 'hit head; concussion; head injury; fell and hit head', 'loss of consciousness; vomiting; severe headache; confusion; seizure; blood/clear fluid from nose/ear; on blood thinners', 'Go to A&E immediately. Keep them still and monitor breathing and alertness.', 'Do not let them sleep it off if symptoms are worsening.', 'Any red flags after head injury.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('suspected_spinal_injury', 'Suspected spinal injury', 'injury', 'AE', 'neck pain after accident; back pain after fall; can''t feel arms/legs; tingling/numbness after accident', 'weakness; loss of bladder/bowel control; major trauma', 'Go to A&E immediately. Keep them still; support the head/neck in the position found; call for emergency help.', 'Do not move them unless there is immediate danger (fire, etc.).', 'Any numbness/weakness after trauma.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('severe_burns_chemical_or_electrical_burns', 'Severe burns / chemical or electrical burns', 'injury', 'AE', 'burn on face; burn on genitals; chemical burn; electrical burn; large burn; burn with breathing trouble', 'large area; deep/charred skin; breathing difficulty; child/elderly', 'Cool the burn with cool running water (not ice) if safe. Remove jewellery if not stuck. Cover loosely with a clean dressing. Go to A&E now.', 'Do not apply ice, butter, toothpaste, or creams. Do not burst blisters.', 'Any large/deep burn or burns to face/airway/genitals or chemical/electrical burns.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('choking_cannot_breathe_speak', 'Choking (cannot breathe/speak)', 'critical', 'AE', 'choking; can''t breathe; can''t talk; turning blue; clutching throat', 'unable to cough effectively; becoming drowsy/unresponsive', 'If they can cough and speak, encourage coughing. If they cannot breathe/speak/cough, seek emergency help and perform appropriate first aid (back blows/abdominal thrusts if trained). Go to A&E now.', 'Do not do blind finger sweeps.', 'Any episode where they couldn''t breathe/speak; if symptoms persist.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('severe_abdominal_pain', 'Severe abdominal pain', 'gi', 'AE', 'severe stomach pain; severe abdominal pain; rigid abdomen; pain with fainting', 'sudden severe pain; vomiting blood; black/tarry stools; pregnancy with pain/bleeding; pain with fever and worsening', 'Go to A&E now, especially if severe or worsening. Rest and avoid food until assessed.', 'Do not take strong painkillers that may mask symptoms unless advised by a clinician.', 'Severe/worsening pain or any red flags.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('poisoning_overdose_swallowed_chemical', 'Poisoning / overdose / swallowed chemical', 'toxicology', 'AE', 'poisoned; overdose; swallowed detergent; swallowed bleach; swallowed unknown pills; inhaled toxic fumes', 'drowsy/confused; trouble breathing; seizure; burns around mouth; unknown amount', 'Go to A&E immediately. If safe, move to fresh air (for fumes). Keep packaging/labels for clinicians.', 'Do not force vomiting or give food/drink unless advised by professionals.', 'Any suspected overdose/poisoning, especially with symptoms.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('drowning_near_drowning', 'Drowning / near drowning', 'critical', 'AE', 'drowning; inhaled water; near drowning', 'coughing persistently; breathing difficulty; sleepiness/confusion', 'Go to A&E immediately. Keep them warm. If not breathing normally, start CPR and use an AED if available.', 'Do not assume they are fine even if they seem better.', 'Any inhalation of water with cough/breathing issues.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('severe_dehydration_heat_stroke', 'Severe dehydration / heat stroke', 'environment', 'AE', 'heat stroke; very hot and confused; stopped sweating and confused; collapsed in heat', 'confusion; fainting; very high temperature; seizure', 'Move to a cool place, loosen clothing, cool with wet cloths/fan, and seek A&E urgently.', 'Do not give fluids if they are drowsy or vomiting repeatedly.', 'Any confusion/fainting/seizure in the heat.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('asthma_flare_mild_moderate', 'Asthma flare (mild/moderate)', 'respiratory', 'POLYCLINIC', 'asthma attack; wheezing; tight chest; short of breath; reliever inhaler not helping much', 'severe breathing difficulty; blue lips; can''t speak', 'Use prescribed reliever inhaler as directed and sit upright. If symptoms do not improve quickly or worsen, go to A&E.', 'Do not ignore worsening symptoms.', 'Same-day review if needing reliever more than usual or symptoms persist.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('fever_child_teen', 'Fever (child/teen)', 'infectious', 'POLYCLINIC', 'fever; high temperature; chills', 'stiff neck; rash that doesn''t fade when pressed; trouble breathing; very sleepy/confused; severe headache; dehydration', 'Rest, drink fluids, and use fever medicine only as directed on the label. Seek same-day care if fever is high or not improving, or any red flags.', 'Do not exceed medicine doses. Avoid aspirin in children/teens unless a doctor says so.', 'Same-day care if persistent high fever or red flags.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('dehydration_mild_moderate', 'Dehydration (mild/moderate)', 'general', 'POLYCLINIC', 'dehydrated; dark urine; dizzy when standing; dry mouth', 'fainting; confusion; no urine for long time; unable to keep fluids down', 'Sip oral rehydration solution or water frequently. Rest in a cool place.', 'Do not chug large amounts quickly if nauseous.', 'Same-day care if ongoing vomiting/diarrhea or worsening dizziness.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('deep_cut_needing_stitches', 'Deep cut needing stitches', 'injury', 'POLYCLINIC', 'deep cut; gaping wound; need stitches', 'bleeding won''t stop; numbness; weakness in limb', 'Apply direct pressure and cover with a clean dressing. Keep the wound clean and go to a clinic/polyclinic soon.', 'Do not use cotton wool directly on the wound.', 'Same-day care for deep/gaping wounds or if dirty/animal bite.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('possible_fracture_stable', 'Possible fracture (stable)', 'injury', 'POLYCLINIC', 'possible broken bone; swollen painful limb after fall; cannot use limb well', 'open wound with bone; blue/cold fingers or toes; severe deformity', 'Immobilise with a splint/sling in the position found, apply a cold pack wrapped in cloth, and seek same-day assessment.', 'Do not try to straighten the limb.', 'Same-day care for suspected fractures; A&E if red flags.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('sprain_strain_can_walk', 'Sprain / strain (can walk)', 'injury', 'GP', 'sprain; twisted ankle; muscle strain; swollen joint after twist', 'cannot bear weight; severe deformity; numb/cold toes/fingers', 'Rest, cold pack (wrapped), light compression if you know how, and elevate. Gradually return to activity as pain improves.', 'Do not apply heat in the first 24 hours.', 'See a clinic/polyclinic same day if you cannot bear weight or pain is severe.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('nosebleed', 'Nosebleed', 'ent', 'GP', 'nosebleed; blood from nose', 'bleeding >20 minutes; heavy bleeding; after head injury; on blood thinners; feeling faint', 'Sit upright and lean forward. Pinch the soft part of the nose continuously for 10 minutes. Spit blood out (don’t swallow).', 'Do not tilt head back. Do not keep checking by releasing the pinch early.', 'Seek care if it won’t stop, is heavy, or follows injury.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('fainting_simple', 'Fainting (simple)', 'general', 'GP', 'fainted; passed out briefly; lightheaded then fainted', 'chest pain; breathing trouble; injury; seizure-like movements; pregnancy; repeated episodes', 'Lie them down and raise legs if possible. Loosen tight clothing and ensure fresh air. When awake, sip water slowly.', 'Do not stand them up quickly.', 'Seek same-day care if it’s the first episode or any red flags.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('vomiting_and_or_diarrhoea', 'Vomiting and/or diarrhoea', 'gi', 'GP', 'vomiting; diarrhea; stomach bug; food poisoning', 'blood in vomit/stool; severe dehydration; severe abdominal pain; high fever; persistent >24–48h', 'Sip oral rehydration solution or water often. Eat bland foods when able.', 'Do not take anti-diarrhoea meds if there is fever or blood in stool unless a clinician advises.', 'See a clinic if persistent, severe, or signs of dehydration.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('eye_irritation_foreign_body_mild', 'Eye irritation / foreign body (mild)', 'eye', 'GP', 'something in eye; eye irritation; grit in eye; eye redness', 'chemical splash; vision changes; severe pain; embedded object', 'Rinse the eye with clean water or saline for several minutes. Remove contact lenses if easy.', 'Do not rub the eye. Do not try to remove an embedded object.', 'A&E for chemical splash or vision loss; otherwise see a clinic if pain/redness persists.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('minor_burns_small_superficial', 'Minor burns (small, superficial)', 'injury', 'GP', 'small burn; small scald; minor blister', 'large area; face/eye/genitals; chemical/electrical; breathing problems', 'Cool with cool running water, cover loosely with a clean dressing, and monitor. Seek clinic care if blistering or pain persists.', 'Do not apply ice or home remedies.', 'Same-day care if blistering, on hands/feet/joints, or signs of infection.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('animal_bite_dog_cat', 'Animal bite (dog/cat)', 'injury', 'POLYCLINIC', 'dog bite; cat bite; animal bite', 'deep puncture; cannot stop bleeding; signs of infection; unknown vaccination status', 'Wash the wound under running water with soap. Apply pressure if bleeding. Cover with a clean dressing. Seek same-day care for assessment and tetanus/rabies advice.', 'Do not seal tightly if it’s dirty; keep it clean and covered lightly.', 'Same-day care for most bites, especially deep bites.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('insect_sting_mild', 'Insect sting (mild)', 'allergy', 'SELF_CARE', 'bee sting; wasp sting; insect sting', 'trouble breathing; face/lip swelling; widespread hives; fainting', 'Remove the stinger if present by scraping (not squeezing). Wash area and apply a cold pack. Consider an antihistamine if allowed.', 'Do not squeeze the stinger.', 'A&E if any breathing trouble or widespread reaction.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('minor_cut_scrape', 'Minor cut / scrape', 'injury', 'SELF_CARE', 'small cut; scrape; abrasion; minor wound', 'won''t stop bleeding after 10 minutes pressure; deep/gaping; animal/human bite', 'Rinse under clean running water, apply gentle pressure to stop bleeding, then cover with a clean dressing.', 'Do not use harsh chemicals directly in the wound.', 'See a clinic if deep/dirty, signs of infection, or tetanus not up to date.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('mild_headache', 'Mild headache', 'general', 'SELF_CARE', 'headache; tension headache', 'sudden worst headache; neck stiffness; fever with rash; after head injury; weakness/numbness; vision changes', 'Rest, hydrate, and use pain relief only as directed on the label. Reduce screen time and bright light if it helps.', 'Do not exceed dosing. Avoid mixing medicines with the same ingredient.', 'Same-day care if headache is severe, unusual, or with red flags.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('sore_throat_cold_symptoms', 'Sore throat / cold symptoms', 'infectious', 'SELF_CARE', 'sore throat; runny nose; cough; cold', 'trouble breathing; drooling/inability to swallow; dehydration; persistent high fever', 'Rest, fluids, warm drinks, and simple remedies (saltwater gargle if appropriate). Seek care if worsening or not improving in a few days.', 'Do not share medicines. Follow label directions.', 'See a clinic if severe pain, persistent fever, or dehydration.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('mild_rash_itch_no_breathing_issues', 'Mild rash / itch (no breathing issues)', 'skin', 'SELF_CARE', 'rash; itchy skin; hives', 'trouble breathing; swollen lips/tongue; rapid worsening; fever with rash', 'Avoid triggers, cool compress, and consider an antihistamine if allowed. Monitor for worsening.', 'Do not use strong steroid creams on the face unless a clinician says so.', 'Seek urgent care if swelling/breathing trouble or fever with rash.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('dental_pain_toothache', 'Dental pain / toothache', 'dental', 'GP', 'toothache; dental pain; gum swelling', 'face swelling; fever; trouble swallowing/breathing', 'Rinse mouth with warm salt water, use pain relief as directed, and arrange a dental visit soon.', 'Do not place aspirin directly on gums (can burn).', 'A&E if face swelling with swallowing/breathing trouble; otherwise dentist/clinic soon.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('minor_allergic_reaction_no_breathing_trouble', 'Minor allergic reaction (no breathing trouble)', 'allergy', 'SELF_CARE', 'mild allergy; sneezing; itchy eyes; mild hives', 'trouble breathing; throat tightness; dizziness/fainting', 'Move away from the trigger, wash exposed skin, and consider an antihistamine if allowed. Monitor.', 'Do not ignore any new breathing symptoms.', 'Seek urgent care if any breathing trouble or swelling of lips/tongue.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('ear_pain', 'Ear pain', 'ent', 'GP', 'earache; ear pain; blocked ear', 'high fever; severe dizziness; ear discharge; swelling behind ear', 'Use pain relief as directed and avoid inserting objects. Seek clinic care if persistent or with fever/discharge.', 'Do not use cotton buds inside the ear canal.', 'Same-day care if severe pain, fever, or discharge.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('urinary_symptoms', 'Urinary symptoms', 'uro', 'GP', 'pain when peeing; burning urine; urinary frequency; lower tummy pain', 'fever with flank pain; vomiting; pregnancy; blood in urine', 'Drink fluids and seek clinic care for testing and treatment.', 'Do not delay if fever or back/flank pain.', 'Polyclinic/A&E if fever + flank pain or vomiting.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('back_pain_no_trauma', 'Back pain (no trauma)', 'msk', 'GP', 'back pain; lower back pain', 'weakness/numbness; loss of bladder/bowel control; fever; history of cancer; after major trauma', 'Stay gently active within pain limits, use heat/cold if helpful, and use pain relief as directed.', 'Do not do heavy lifting while acute pain is severe.', 'A&E if weakness/numbness or bladder/bowel changes; otherwise clinic if persistent.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('minor_asthma_cough_at_night', 'Minor asthma/cough at night', 'respiratory', 'GP', 'cough at night; mild wheeze; mild shortness of breath', 'severe shortness of breath; blue lips; can''t speak', 'Use prescribed inhaler as directed and monitor. Arrange clinic review if symptoms recur or affect sleep.', 'Do not overuse reliever without medical advice.', 'Same-day care if worsening or frequent reliever use.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('finger_toe_injury_jammed', 'Finger/toe injury (jammed)', 'injury', 'GP', 'jammed finger; stubbed toe; finger swelling after sports', 'deformity; severe pain; cannot move; numb/cold digit', 'Rest, cold pack wrapped in cloth, and buddy-tape if comfortable and no deformity. Seek assessment if pain/swelling is significant.', 'Do not force movement.', 'Same-day care if deformity or unable to move.');
INSERT INTO triage_rules (id, topic, category, destination, trigger_any, red_flags_any, immediate_actions, do_not, seek_care_soon_if)
VALUES ('menstrual_cramps', 'Menstrual cramps', 'general', 'SELF_CARE', 'period cramps; menstrual pain', 'very heavy bleeding; fainting; severe one-sided pain; pregnancy possibility', 'Heat pack on lower abdomen and pain relief as directed on the label. Rest and hydrate.', 'Do not exceed medicine dosing.', 'See a clinician if pain is new/severe or bleeding is very heavy.');
